"""Remove document role

Revision ID: 5229ddb8b57e
Revises: ee86ab734e7f
Create Date: 2026-08-09 19:41:17.869096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5229ddb8b57e'
down_revision: Union[str, Sequence[str], None] = 'ee86ab734e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
